"""``anchor init`` — choose an AI provider (and thus a data zone) for a project.

The provider choice IS the data-boundary choice: ``local``/``ollama`` keep
document content on your network, ``azure``/``custom`` send it only to the
endpoint you name, ``openai`` is public. init writes those choices to a
non-secret ``anchor.toml`` that the CLI, server, and an agent-launched
``anchor-mcp`` all resolve. The API key is never written here — it stays in
``ANCHOR_OPENAI_API_KEY`` / a gitignored ``.env``.

Interactive on a tty; unattended under ``--yes`` or a non-interactive stdin
(an agent passes ``--provider`` + flags), so it never blocks.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import typer

from anchor.infra.config import CONFIG_FILENAME, AnchorConfig
from anchor.infra.providers import (
    PROVIDERS,
    Provider,
    embed_options_for,
    get_provider,
    normalize_base_url,
)


def _is_readable_toml(path: Path) -> bool:
    """True when the file parses as TOML; False for missing/corrupt files."""
    import tomllib

    try:
        with path.open("rb") as handle:
            tomllib.load(handle)
        return True
    except Exception:  # noqa: BLE001 - any read/parse failure means "replace it"
        return False


def _toml_escape(value: str) -> str:
    # Drop control characters first (e.g. a stray ANSI escape captured when a
    # user presses an arrow key at a text prompt). They are illegal in a TOML
    # basic string, so leaving them in would write a file that won't parse back.
    cleaned = "".join(ch for ch in value if ch >= " " and ch != "\x7f")
    return cleaned.replace("\\", "\\\\").replace('"', '\\"')


def _render_toml(fields: dict[str, str]) -> str:
    lines = [
        "# Anchor project configuration (non-secret).",
        "# Generated by `anchor init`. The API key is NOT stored here. Set",
        "# ANCHOR_OPENAI_API_KEY in your environment or a gitignored .env.",
        "",
    ]
    lines.extend(f'{key} = "{_toml_escape(val)}"' for key, val in fields.items())
    return "\n".join(lines) + "\n"


def _ask(label: str, default: str, *, interactive: bool) -> str:
    return typer.prompt(label, default=default) if interactive else default


# Providers that authenticate against an endpoint and therefore need an API key.
_KEYED_PROVIDERS = ("openai", "azure", "custom")


def _anchor_key_present(target: Path) -> bool:
    """True when ANCHOR_OPENAI_API_KEY is already available (env or this .env)."""
    if os.environ.get("ANCHOR_OPENAI_API_KEY"):
        return True
    env_file = target / ".env"
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("ANCHOR_OPENAI_API_KEY=") and stripped.split("=", 1)[1].strip():
                return True
    return False


def _ensure_gitignored(target: Path, entry: str) -> None:
    """Make sure ``entry`` is in this folder's .gitignore (create if needed)."""
    gi = target / ".gitignore"
    existing = gi.read_text(encoding="utf-8").splitlines() if gi.exists() else []
    if entry in (line.strip() for line in existing):
        return
    with gi.open("a", encoding="utf-8") as handle:
        if existing and existing[-1].strip():
            handle.write("\n")
        handle.write(f"{entry}\n")


def _write_env_key(target: Path, key: str) -> Path:
    """Append ANCHOR_OPENAI_API_KEY to a gitignored .env, return its path."""
    env_file = target / ".env"
    line = f"ANCHOR_OPENAI_API_KEY={key}"
    prior = env_file.read_text(encoding="utf-8") if env_file.exists() else ""
    sep = "" if (not prior or prior.endswith("\n")) else "\n"
    with env_file.open("a", encoding="utf-8") as handle:
        handle.write(f"{sep}{line}\n")
    _ensure_gitignored(target, ".env")
    # Reflect it in-process so the readback below shows the key as detected.
    os.environ["ANCHOR_OPENAI_API_KEY"] = key
    return env_file


def _setup_api_key(target: Path, prov: Provider, *, interactive: bool) -> None:
    """Help the user get a key in place — the one thing init can't put in the toml.

    Offers to capture the key into a gitignored .env (never the committed toml).
    Warns when only a personal ``OPENAI_API_KEY`` is set, since that is the wrong
    credential for an Azure/custom endpoint and would otherwise look fine.
    """
    if prov.key not in _KEYED_PROVIDERS or _anchor_key_present(target):
        return
    personal = bool(os.environ.get("OPENAI_API_KEY"))
    # For public OpenAI, OPENAI_API_KEY is the correct credential — nothing to do.
    if prov.key == "openai" and personal:
        return
    # For a named endpoint, a personal key is the WRONG credential and would
    # otherwise look fine until the first call fails. Say so.
    if prov.key in ("azure", "custom") and personal:
        typer.echo(
            "  ! A personal OPENAI_API_KEY is set, but it is NOT the right "
            f"credential for {prov.label} — ANCHOR uses ANCHOR_OPENAI_API_KEY here."
        )
    if not interactive:
        return
    key = typer.prompt(
        f"Paste your {prov.label} API key to save it to a gitignored .env "
        "(or press Enter to set it yourself later)",
        default="",
        hide_input=True,
        show_default=False,
    ).strip()
    if key:
        env_file = _write_env_key(target, key)
        typer.echo(f"  Saved your key to {env_file} (.env is gitignored).")


def _default(field: str) -> str:
    return str(AnchorConfig.model_fields[field].default)


def _provider_choice_label(p: Provider) -> str:
    tag = "" if p.available else "   (config only — endpoint client pending)"
    return f"{p.label} — {p.zone}{tag}"


def _choose(message: str, items: list, render, *, interactive: bool):
    """Arrow-key select one of ``items`` (questionary), with a numbered fallback.

    ``render(item) -> str`` produces each label. Returns the chosen item.
    """
    if not interactive:
        return items[0]
    try:
        import questionary
    except ImportError:
        questionary = None
    if questionary is not None:
        answer = questionary.select(
            message,
            choices=[questionary.Choice(title=render(it), value=i) for i, it in enumerate(items)],
            instruction="(↑/↓ to move, Enter to choose)",
            qmark="▍",
            pointer="❯",
        ).ask()
        if answer is None:  # Ctrl-C / no tty
            raise typer.Exit(code=1)
        return items[answer]
    # Plain numbered fallback.
    typer.echo(message)
    for i, it in enumerate(items, start=1):
        typer.echo(f"  {i}. {render(it)}")
    while True:
        raw = typer.prompt(f"[1-{len(items)}]", default="1")
        try:
            idx = int(raw)
        except ValueError:
            idx = 0
        if 1 <= idx <= len(items):
            return items[idx - 1]
        typer.echo("Enter a number from the list.")


def _resolve_provider(flag: str | None, *, interactive: bool) -> Provider:
    """Pick a provider from the flag, an interactive menu, or the safe default."""
    if flag:
        provider = get_provider(flag)
        if provider is None:
            valid = ", ".join(p.key for p in PROVIDERS)
            typer.echo(f"Unknown provider '{flag}'. Choose one of: {valid}", err=True)
            raise typer.Exit(code=2)
        return provider
    if not interactive:
        # Default to the zero-egress option when nothing is specified.
        return get_provider("local")  # type: ignore[return-value]
    return _choose("Where may document content go?", list(PROVIDERS), _provider_choice_label,
                   interactive=interactive)


def _resolve_embed_model(flag: str | None, provider: Provider, *, interactive: bool) -> str:
    """Pick the embedding model, with options that depend on the provider.

    Local providers keep vectors on-host (single bge option). Endpoint
    providers additionally offer remote embeddings, which send text out.
    """
    if flag:
        return flag
    options = embed_options_for(provider)
    if len(options) == 1 or not interactive:
        return options[0].model
    return _choose(
        "Embedding model — where do the vectors compute?",
        list(options),
        lambda o: o.label,
        interactive=interactive,
    ).model


def init(
    directory: Path = typer.Argument(Path("."), help="Project folder to write anchor.toml into."),
    provider: str = typer.Option(None, "--provider", help="local|ollama|openai|azure|custom."),
    data_dir: str = typer.Option(None, "--data-dir", help="Where bronze/silver/gold/canvases live."),
    embed_model: str = typer.Option(None, "--embed-model", help="Local embedding model id."),
    base_url: str = typer.Option(None, "--base-url", help="Endpoint for the chosen provider."),
    vision_model: str = typer.Option(
        None, "--vision-model", help="Model / deployment for polish + region extraction."
    ),
    docling_device: str = typer.Option(None, "--docling-device", help="cpu|cuda|mps|auto."),
    yes: bool = typer.Option(False, "--yes", "-y", help="Accept defaults, no prompts."),
    force: bool = typer.Option(False, "--force", help="Overwrite an existing anchor.toml."),
) -> None:
    """Choose an AI provider/data-zone for this project and write anchor.toml."""
    target = directory.expanduser().resolve()
    config_path = target / CONFIG_FILENAME
    if config_path.exists() and not force:
        if _is_readable_toml(config_path):
            typer.echo(f"{config_path} already exists. Re-run with --force to overwrite.", err=True)
            raise typer.Exit(code=1)
        # A corrupt config is not worth protecting — replace it without --force.
        typer.echo(f"Replacing unreadable {config_path} (it does not parse).", err=True)

    # Prompt only on a real terminal without --yes; otherwise run off flags.
    interactive = not yes and sys.stdin.isatty()
    prov = _resolve_provider(provider, interactive=interactive)

    # Default the data dir into THIS project, not the global ~/anchor-data —
    # `init` scaffolds a self-contained folder, so its knowledge base lives
    # alongside it (absolute, so an agent-launched anchor-mcp resolves it from
    # anywhere via the toml). Override at the prompt or with --data-dir.
    default_data_dir = str(target / "anchor-data")
    fields: dict[str, str] = {
        "provider": prov.key,
        "data_dir": data_dir or _ask("Data directory", default_data_dir, interactive=interactive),
        "embed_model": _resolve_embed_model(embed_model, prov, interactive=interactive),
        "docling_device": docling_device
        or _ask("Docling device (cpu|cuda|mps|auto)", _default("docling_device"), interactive=interactive),
    }

    if prov.does_vision:
        if prov.base_url_required:
            resolved_url = base_url or _ask(
                f"{prov.label} endpoint base URL", "", interactive=interactive
            )
            if not resolved_url:
                typer.echo(
                    f"Provider '{prov.key}' needs an endpoint — pass --base-url <url>.", err=True
                )
                raise typer.Exit(code=2)
        else:
            resolved_url = base_url if base_url is not None else (prov.default_base_url or "")
        normalized_url = normalize_base_url(prov.key, resolved_url)
        if normalized_url and normalized_url != resolved_url.strip():
            typer.echo(f"  Adjusted endpoint to {normalized_url} (Azure serves the API under /openai/v1/).")
        if normalized_url:
            fields["openai_base_url"] = normalized_url
        chosen_model = vision_model or _ask(
            "Vision model / deployment (polish + regions)",
            prov.default_vision_model or _default("polish_model"),
            interactive=interactive,
        )
        # polish and region default to the same model; advanced users split in the toml.
        fields["polish_model"] = chosen_model
        fields["region_model"] = chosen_model

    target.mkdir(parents=True, exist_ok=True)
    # Always UTF-8: TOML mandates it, and the default locale encoding on
    # Windows (cp1252) would write a non-ASCII char such as an em-dash as a
    # byte the UTF-8 reader rejects, silently dropping the whole config.
    config_path.write_text(_render_toml(fields), encoding="utf-8")
    _setup_api_key(target, prov, interactive=interactive)
    _report(config_path, target, prov)


def _report(config_path: Path, target: Path, prov: Provider) -> None:
    """Echo the recorded config, honestly distinguishing applied vs not-yet."""
    # Pin ANCHOR_CONFIG so the readback reflects the file we just wrote.
    prev = os.environ.get("ANCHOR_CONFIG")
    os.environ["ANCHOR_CONFIG"] = str(config_path)
    try:
        cfg = AnchorConfig()
    finally:
        if prev is None:
            os.environ.pop("ANCHOR_CONFIG", None)
        else:
            os.environ["ANCHOR_CONFIG"] = prev

    # Only ANCHOR_OPENAI_API_KEY (env or .env) is actually used for the endpoint;
    # a stray personal OPENAI_API_KEY is NOT, so don't count it as "set".
    has_anchor_key = bool(cfg.openai_api_key)
    typer.echo(f"Wrote {config_path}")
    typer.echo("")
    typer.echo(f"Provider : {prov.label}")
    typer.echo(f"Data zone: {prov.zone}")
    if prov.note:
        typer.echo(f"Note     : {prov.note}")
    if not prov.available:
        typer.echo("  ! Endpoint client not implemented yet — recorded but won't run until #48.")
    typer.echo("")
    # These fields are read by every adapter without being passed explicitly,
    # so the values below are what those processes will actually use.
    embed_remote = cfg.embed_model.startswith("text-embedding-")
    embed_tag = "remote — vectors computed at your endpoint" if embed_remote else "local, no egress"
    typer.echo("Applied automatically (CLI, server, anchor-mcp):")
    typer.echo(f"  data dir       : {cfg.data_dir}")
    typer.echo(f"  embed model    : {cfg.embed_model}  ({embed_tag})")
    needs_key = prov.key in _KEYED_PROVIDERS
    # OPENAI_API_KEY is the right credential for public OpenAI, but the wrong one
    # for a named (azure/custom) endpoint — only ANCHOR_OPENAI_API_KEY counts there.
    personal = bool(os.environ.get("OPENAI_API_KEY"))
    key_ok = has_anchor_key or (prov.key == "openai" and personal)
    if prov.does_vision:
        typer.echo(f"  vision endpoint: {cfg.openai_base_url or 'api.openai.com'}")
        typer.echo(f"  vision model   : {cfg.polish_model}")
        if needs_key:
            if has_anchor_key:
                key_state = "ANCHOR_OPENAI_API_KEY detected ✓"
            elif prov.key == "openai" and personal:
                key_state = "using OPENAI_API_KEY ✓"
            else:
                key_state = "NOT set — required (see below)"
            typer.echo(f"  api key        : {key_state}")
    else:
        typer.echo("  vision model   : none — no document content leaves this host")
    typer.echo(f"  docling device : {cfg.docling_device}")
    typer.echo("")
    typer.echo("Next steps (run inside this folder):")
    if needs_key and not key_ok:
        typer.echo("  1. Set your API key (never written to anchor.toml):")
        typer.echo("       echo 'ANCHOR_OPENAI_API_KEY=…' >> .env     # gitignored, this folder")
        typer.echo("     Then verify the endpoint, deployment, and key:")
        typer.echo("       anchor check --probe")
    else:
        typer.echo("  anchor check                 verify the data zone + config")
    typer.echo("  anchor ingest <file.pdf>     add a document to the knowledge base")
    typer.echo(f"  anchor serve                 open the canvas at http://localhost:{cfg.http_port}")
    typer.echo("  anchor install claude-code   let an agent drive ANCHOR over MCP   (optional)")
    typer.echo("")
    # The CLI/server resolve config by running inside this folder; a standalone
    # anchor-mcp launched elsewhere needs ANCHOR_CONFIG to find it.
    typer.echo(
        f"Other tools read this config when run inside {target}; an agent-launched "
        f"anchor-mcp needs ANCHOR_CONFIG={config_path}."
    )
