"""``anchor init`` — choose an AI provider (and thus a data zone) for a project.

The provider choice IS the data-boundary choice: ``local``/``ollama`` keep
document content on your network, ``azure``/``custom`` send it only to the
endpoint you name, ``openai`` is public. init writes those choices to a
non-secret ``anchor.toml`` that the CLI, server, and an agent-launched
``anchor-mcp`` all resolve. The API key is never written here — it stays in
``ANCHOR_OPENAI_API_KEY`` / a gitignored ``.env``.

Interactive on a tty; unattended under ``--yes`` or a non-interactive stdin
(an agent passes ``--provider`` + flags), so it never blocks.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import typer

from anchor.infra.config import CONFIG_FILENAME, AnchorConfig
from anchor.infra.providers import PROVIDERS, Provider, embed_options_for, get_provider


def _toml_escape(value: str) -> str:
    # Drop control characters first (e.g. a stray ANSI escape captured when a
    # user presses an arrow key at a text prompt). They are illegal in a TOML
    # basic string, so leaving them in would write a file that won't parse back.
    cleaned = "".join(ch for ch in value if ch >= " " and ch != "\x7f")
    return cleaned.replace("\\", "\\\\").replace('"', '\\"')


def _render_toml(fields: dict[str, str]) -> str:
    lines = [
        "# Anchor project configuration (non-secret).",
        "# Generated by `anchor init`. The API key is NOT stored here — set",
        "# ANCHOR_OPENAI_API_KEY in your environment or a gitignored .env.",
        "",
    ]
    lines.extend(f'{key} = "{_toml_escape(val)}"' for key, val in fields.items())
    return "\n".join(lines) + "\n"


def _ask(label: str, default: str, *, interactive: bool) -> str:
    return typer.prompt(label, default=default) if interactive else default


def _default(field: str) -> str:
    return str(AnchorConfig.model_fields[field].default)


def _provider_choice_label(p: Provider) -> str:
    tag = "" if p.available else "   (config only — endpoint client pending)"
    return f"{p.label} — {p.zone}{tag}"


def _choose(message: str, items: list, render, *, interactive: bool):
    """Arrow-key select one of ``items`` (questionary), with a numbered fallback.

    ``render(item) -> str`` produces each label. Returns the chosen item.
    """
    if not interactive:
        return items[0]
    try:
        import questionary
    except ImportError:
        questionary = None
    if questionary is not None:
        answer = questionary.select(
            message,
            choices=[questionary.Choice(title=render(it), value=i) for i, it in enumerate(items)],
            instruction="(↑/↓ to move, Enter to choose)",
            qmark="▍",
            pointer="❯",
        ).ask()
        if answer is None:  # Ctrl-C / no tty
            raise typer.Exit(code=1)
        return items[answer]
    # Plain numbered fallback.
    typer.echo(message)
    for i, it in enumerate(items, start=1):
        typer.echo(f"  {i}. {render(it)}")
    while True:
        raw = typer.prompt(f"[1-{len(items)}]", default="1")
        try:
            idx = int(raw)
        except ValueError:
            idx = 0
        if 1 <= idx <= len(items):
            return items[idx - 1]
        typer.echo("Enter a number from the list.")


def _resolve_provider(flag: str | None, *, interactive: bool) -> Provider:
    """Pick a provider from the flag, an interactive menu, or the safe default."""
    if flag:
        provider = get_provider(flag)
        if provider is None:
            valid = ", ".join(p.key for p in PROVIDERS)
            typer.echo(f"Unknown provider '{flag}'. Choose one of: {valid}", err=True)
            raise typer.Exit(code=2)
        return provider
    if not interactive:
        # Default to the zero-egress option when nothing is specified.
        return get_provider("local")  # type: ignore[return-value]
    return _choose("Where may document content go?", list(PROVIDERS), _provider_choice_label,
                   interactive=interactive)


def _resolve_embed_model(flag: str | None, provider: Provider, *, interactive: bool) -> str:
    """Pick the embedding model, with options that depend on the provider.

    Local providers keep vectors on-host (single bge option). Endpoint
    providers additionally offer remote embeddings, which send text out.
    """
    if flag:
        return flag
    options = embed_options_for(provider)
    if len(options) == 1 or not interactive:
        return options[0].model
    return _choose(
        "Embedding model — where do the vectors compute?",
        list(options),
        lambda o: o.label,
        interactive=interactive,
    ).model


def init(
    directory: Path = typer.Argument(Path("."), help="Project folder to write anchor.toml into."),
    provider: str = typer.Option(None, "--provider", help="local|ollama|openai|azure|custom."),
    data_dir: str = typer.Option(None, "--data-dir", help="Where bronze/silver/gold/canvases live."),
    embed_model: str = typer.Option(None, "--embed-model", help="Local embedding model id."),
    base_url: str = typer.Option(None, "--base-url", help="Endpoint for the chosen provider."),
    vision_model: str = typer.Option(
        None, "--vision-model", help="Model / deployment for polish + region extraction."
    ),
    docling_device: str = typer.Option(None, "--docling-device", help="cpu|cuda|mps|auto."),
    yes: bool = typer.Option(False, "--yes", "-y", help="Accept defaults, no prompts."),
    force: bool = typer.Option(False, "--force", help="Overwrite an existing anchor.toml."),
) -> None:
    """Choose an AI provider/data-zone for this project and write anchor.toml."""
    target = directory.expanduser().resolve()
    config_path = target / CONFIG_FILENAME
    if config_path.exists() and not force:
        typer.echo(f"{config_path} already exists. Re-run with --force to overwrite.", err=True)
        raise typer.Exit(code=1)

    # Prompt only on a real terminal without --yes; otherwise run off flags.
    interactive = not yes and sys.stdin.isatty()
    prov = _resolve_provider(provider, interactive=interactive)

    # Default the data dir into THIS project, not the global ~/anchor-data —
    # `init` scaffolds a self-contained folder, so its knowledge base lives
    # alongside it (absolute, so an agent-launched anchor-mcp resolves it from
    # anywhere via the toml). Override at the prompt or with --data-dir.
    default_data_dir = str(target / "anchor-data")
    fields: dict[str, str] = {
        "provider": prov.key,
        "data_dir": data_dir or _ask("Data directory", default_data_dir, interactive=interactive),
        "embed_model": _resolve_embed_model(embed_model, prov, interactive=interactive),
        "docling_device": docling_device
        or _ask("Docling device (cpu|cuda|mps|auto)", _default("docling_device"), interactive=interactive),
    }

    if prov.does_vision:
        if prov.base_url_required:
            resolved_url = base_url or _ask(
                f"{prov.label} endpoint base URL", "", interactive=interactive
            )
            if not resolved_url:
                typer.echo(
                    f"Provider '{prov.key}' needs an endpoint — pass --base-url <url>.", err=True
                )
                raise typer.Exit(code=2)
        else:
            resolved_url = base_url if base_url is not None else (prov.default_base_url or "")
        if resolved_url:
            fields["openai_base_url"] = resolved_url
        chosen_model = vision_model or _ask(
            "Vision model / deployment (polish + regions)",
            prov.default_vision_model or _default("polish_model"),
            interactive=interactive,
        )
        # polish and region default to the same model; advanced users split in the toml.
        fields["polish_model"] = chosen_model
        fields["region_model"] = chosen_model

    target.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_render_toml(fields))
    _report(config_path, target, prov)


def _report(config_path: Path, target: Path, prov: Provider) -> None:
    """Echo the recorded config, honestly distinguishing applied vs not-yet."""
    # Pin ANCHOR_CONFIG so the readback reflects the file we just wrote.
    prev = os.environ.get("ANCHOR_CONFIG")
    os.environ["ANCHOR_CONFIG"] = str(config_path)
    try:
        cfg = AnchorConfig()
    finally:
        if prev is None:
            os.environ.pop("ANCHOR_CONFIG", None)
        else:
            os.environ["ANCHOR_CONFIG"] = prev

    has_key = bool(cfg.openai_api_key) or bool(os.environ.get("OPENAI_API_KEY"))
    typer.echo(f"Wrote {config_path}")
    typer.echo("")
    typer.echo(f"Provider : {prov.label}")
    typer.echo(f"Data zone: {prov.zone}")
    if prov.note:
        typer.echo(f"Note     : {prov.note}")
    if not prov.available:
        typer.echo("  ! Endpoint client not implemented yet — recorded but won't run until #48.")
    typer.echo("")
    # These fields are read by every adapter without being passed explicitly,
    # so the values below are what those processes will actually use.
    embed_remote = cfg.embed_model.startswith("text-embedding-")
    embed_tag = "remote — vectors computed at your endpoint" if embed_remote else "local, no egress"
    typer.echo("Applied automatically (CLI, server, anchor-mcp):")
    typer.echo(f"  data dir       : {cfg.data_dir}")
    typer.echo(f"  embed model    : {cfg.embed_model}  ({embed_tag})")
    if prov.does_vision:
        typer.echo(f"  vision endpoint: {cfg.openai_base_url or 'api.openai.com'}")
        typer.echo(f"  vision model   : {cfg.polish_model}")
        if prov.key != "ollama":
            typer.echo(f"  api key in env : {'yes' if has_key else 'not set — export ANCHOR_OPENAI_API_KEY'}")
    else:
        typer.echo("  vision model   : none — no document content leaves this host")
    typer.echo(f"  docling device : {cfg.docling_device}")
    typer.echo("")
    # The CLI/server resolve --data-dir from this config (common.default_data_dir);
    # a standalone anchor-mcp launched elsewhere needs ANCHOR_CONFIG to find it.
    typer.echo(
        f"The CLI and server read this by running inside {target}; for an "
        f"agent-launched anchor-mcp set ANCHOR_CONFIG={config_path}."
    )
