"""AnchorConfig resolves a project anchor.toml, with env taking precedence."""
from __future__ import annotations

from pathlib import Path

from anchor.infra.config import AnchorConfig, discover_config_file

_CLEAR = (
    "ANCHOR_CONFIG",
    "ANCHOR_DATA_DIR",
    "ANCHOR_EMBED_MODEL",
    "ANCHOR_POLISH_MODEL",
    "ANCHOR_DOCLING_DEVICE",
)


def _clean_env(monkeypatch):
    for name in _CLEAR:
        monkeypatch.delenv(name, raising=False)


def test_anchor_toml_discovered_by_walkup(tmp_path, monkeypatch):
    _clean_env(monkeypatch)
    (tmp_path / "anchor.toml").write_text(
        'embed_model = "test-embed"\npolish_model = "test-polish"\n'
    )
    nested = tmp_path / "a" / "b"
    nested.mkdir(parents=True)
    monkeypatch.chdir(nested)

    assert discover_config_file() == tmp_path / "anchor.toml"
    cfg = AnchorConfig()
    assert cfg.embed_model == "test-embed"
    assert cfg.polish_model == "test-polish"


def test_env_overrides_toml(tmp_path, monkeypatch):
    _clean_env(monkeypatch)
    (tmp_path / "anchor.toml").write_text('embed_model = "from-toml"\n')
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("ANCHOR_EMBED_MODEL", "from-env")

    assert AnchorConfig().embed_model == "from-env"


def test_anchor_config_env_points_at_explicit_file(tmp_path, monkeypatch):
    _clean_env(monkeypatch)
    cfg_file = tmp_path / "custom.toml"
    cfg_file.write_text('docling_device = "cuda"\n')
    work = tmp_path / "work"
    work.mkdir()
    monkeypatch.chdir(work)  # no anchor.toml here
    monkeypatch.setenv("ANCHOR_CONFIG", str(cfg_file))

    assert discover_config_file() == cfg_file
    assert AnchorConfig().docling_device == "cuda"


def test_malformed_toml_is_ignored_not_fatal(tmp_path, monkeypatch):
    # Reproduces the field-with-ANSI-escape corruption: an unparseable
    # anchor.toml must warn and fall back, never crash the CLI at import.
    _clean_env(monkeypatch)
    (tmp_path / "anchor.toml").write_text('embed_model = "bad\x1bvalue"\n')
    monkeypatch.chdir(tmp_path)
    cfg = AnchorConfig()  # must not raise
    assert cfg.embed_model == "BAAI/bge-small-en-v1.5"  # fell back to default


def test_missing_config_falls_back_to_defaults(tmp_path, monkeypatch):
    _clean_env(monkeypatch)
    monkeypatch.chdir(tmp_path)
    assert discover_config_file() is None
    assert AnchorConfig().docling_device == "auto"


def test_tilde_in_toml_data_dir_is_expanded(tmp_path, monkeypatch):
    # A data_dir of "~/anchortest2" must expand to $HOME, not create a
    # literal ./~ folder inside the project.
    _clean_env(monkeypatch)
    (tmp_path / "anchor.toml").write_text('data_dir = "~/anchortest2"\n')
    monkeypatch.chdir(tmp_path)

    data_dir = AnchorConfig().data_dir
    assert data_dir == Path.home() / "anchortest2"
    assert "~" not in str(data_dir)


def test_envvar_in_data_dir_is_expanded(tmp_path, monkeypatch):
    _clean_env(monkeypatch)
    monkeypatch.setenv("ANCHOR_DATA_DIR", "$HOME/anchortest2")
    monkeypatch.chdir(tmp_path)

    assert AnchorConfig().data_dir == Path.home() / "anchortest2"


def test_default_data_dir_unaffected(tmp_path, monkeypatch):
    _clean_env(monkeypatch)
    monkeypatch.chdir(tmp_path)
    assert AnchorConfig().data_dir == Path.home() / "anchor-data"


def test_cp1252_toml_still_loads(tmp_path, monkeypatch):
    # A toml written under a Windows locale (cp1252) instead of UTF-8 — an
    # em-dash as byte 0x97 — must still load, not be silently dropped to the
    # default data dir.
    _clean_env(monkeypatch)
    toml = "# generated by anchor init — do not edit\ndata_dir = \"./anchordata\"\n"
    (tmp_path / "anchor.toml").write_bytes(toml.encode("cp1252"))
    monkeypatch.chdir(tmp_path)

    assert AnchorConfig().data_dir == Path("./anchordata")


def test_utf8_bom_toml_still_loads(tmp_path, monkeypatch):
    _clean_env(monkeypatch)
    (tmp_path / "anchor.toml").write_bytes(
        b"\xef\xbb\xbf" + b'embed_model = "from-bom-toml"\n'
    )
    monkeypatch.chdir(tmp_path)

    assert AnchorConfig().embed_model == "from-bom-toml"
