"""Regenerate the checked-in Claude Code plugin artifacts.

The plugin under ``plugins/anchor/`` ships a static copy of the anchor
skill so users can install ANCHOR through the Claude Code plugin
marketplace without running ``anchor install``. The skill text is the
same output ``anchor install claude-code`` writes, composed from the
bundled sources under ``src/anchor/skills/`` by
``anchor.adapters.skills.compose_skill_md``.

This script:

1. Composes ``plugins/anchor/skills/anchor/SKILL.md`` from the bundled
   skill sources only (no third-party OIP producers, so the output is
   deterministic and machine-independent).
2. Syncs the ``version`` field in
   ``plugins/anchor/.claude-plugin/plugin.json`` from ``pyproject.toml``.

Run it after editing ``src/anchor/skills/`` or bumping the version:

    uv run python scripts/build_claude_plugin.py

Then commit the changed files. CI does not regenerate them.
"""
from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGIN_DIR = REPO_ROOT / "plugins" / "anchor"
SKILL_PATH = PLUGIN_DIR / "skills" / "anchor" / "SKILL.md"
MANIFEST_PATH = PLUGIN_DIR / ".claude-plugin" / "plugin.json"

GENERATED_NOTE = (
    "<!-- Generated by scripts/build_claude_plugin.py from src/anchor/skills/.\n"
    "     Do not edit by hand; edit the sources and regenerate. -->"
)


def build_skill_md() -> str:
    """Compose the plugin SKILL.md with a generated-file marker.

    The marker goes after the YAML frontmatter block so Claude Code's
    frontmatter parsing is untouched.
    """
    from anchor.adapters.skills import compose_skill_md

    text = compose_skill_md(third_party_manifests=())
    if text.startswith("---\n"):
        end = text.index("\n---\n", 4) + len("\n---\n")
        return text[:end] + "\n" + GENERATED_NOTE + "\n" + text[end:]
    return GENERATED_NOTE + "\n\n" + text


def sync_version() -> str:
    """Copy the version from pyproject.toml into plugin.json."""
    pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    version = pyproject["project"]["version"]
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    manifest["version"] = version
    MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    return version


def main() -> int:
    SKILL_PATH.parent.mkdir(parents=True, exist_ok=True)
    SKILL_PATH.write_text(build_skill_md(), encoding="utf-8")
    version = sync_version()
    print(f"wrote {SKILL_PATH.relative_to(REPO_ROOT)}")
    print(f"synced plugin version {version} -> {MANIFEST_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
